#!/usr/bin/env node
/*
 * What the app shares with the web apps, written as Dart so it has one source:
 * - lib/theme/tokens.g.dart: the design tokens (packages/ui/src/theme.css: the light
 *   @theme block and its dark twin, the radii) and the avatar colours
 *   (packages/ui/src/avatar-colors.ts);
 * - lib/theme/icons.g.dart: the interface icons (packages/ui/src/icons.tsx);
 * - lib/l10n/badge_texts.g.dart: badge names and descriptions in every language
 *   (packages/i18n/messages/*.json, "badges").
 *
 *   node apps/mobile/tool/shared.mjs           # write
 *   node apps/mobile/tool/shared.mjs --check   # fail if a Dart file is out of date (CI)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const themePath = join(repoRoot, 'packages/ui/src/theme.css');
const avatarColorsPath = join(repoRoot, 'packages/ui/src/avatar-colors.ts');
const outPath = join(here, '../lib/theme/tokens.g.dart');
const iconsPath = join(repoRoot, 'packages/ui/src/icons.tsx');
const iconsOutPath = join(here, '../lib/theme/icons.g.dart');
const badgesOutPath = join(here, '../lib/l10n/badge_texts.g.dart');
const LANGUAGES = ['en', 'ar', 'ur'];

/** "brand-600" → "brand600", "on-primary" → "onPrimary". */
const dartName = (name) => name.replace(/-(\w)/g, (_, c) => c.toUpperCase());

/** "#f5ead8" → 0xFFF5EAD8; "color-mix(in srgb, #201e1d 14%, transparent)" → 0x24201E1D. */
export function argbOf(value, name = '?') {
  const text = value.trim();
  const hex = text.match(/^#([0-9a-f]{6})$/i);
  if (hex) return `0xFF${hex[1].toUpperCase()}`;
  const mix = text.match(/^color-mix\(in srgb,\s*#([0-9a-f]{6})\s+([\d.]+)%,\s*transparent\)$/i);
  if (mix) {
    const alpha = Math.round((Number(mix[2]) / 100) * 255);
    return `0x${alpha.toString(16).padStart(2, '0').toUpperCase()}${mix[1].toUpperCase()}`;
  }
  throw new Error(
    `--${name} must be #rrggbb or color-mix(in srgb, #rrggbb N%, transparent), not "${value}"`,
  );
}

const colorsIn = (block) =>
  [...block.matchAll(/--color-([\w-]+):\s*([^;]+);/g)].map(([, name, value]) => ({
    name: dartName(name),
    argb: argbOf(value, `color-${name}`),
  }));

/** The light colours (@theme), their dark twins (prefers-color-scheme: dark) and the radii. */
export function readTokens(css) {
  const light = css.match(/@theme\s*\{([\s\S]*?)\n\}/);
  if (!light) throw new Error('No @theme block in theme.css');
  const dark = css.match(/@media \(prefers-color-scheme: dark\)\s*\{\s*:root\s*\{([\s\S]*?)\n  \}/);
  if (!dark) throw new Error('No dark block (@media (prefers-color-scheme: dark)) in theme.css');
  const colors = colorsIn(light[1]);
  const darkColors = new Map(colorsIn(dark[1]).map(({ name, argb }) => [name, argb]));
  const missing = colors.filter(({ name }) => !darkColors.has(name)).map(({ name }) => name);
  if (missing.length > 0) throw new Error(`No dark colour for: ${missing.join(', ')}`);
  const radii = [...light[1].matchAll(/--radius-([\w-]+):\s*([\d.]+)rem;/g)].map(
    ([, name, rem]) => ({ name: dartName(name), px: Number(rem) * 16 }),
  );
  if (colors.length === 0 || !radii.some(({ name }) => name === 'card'))
    throw new Error('theme.css has no colours or --radius-card');
  return {
    colors: colors.map(({ name, argb }) => ({ name, light: argb, dark: darkColors.get(name) })),
    radii,
  };
}

/** The avatars' background colours: `rocket: '#4f46e5',` lines of AVATAR_COLORS. */
export function readAvatarColors(source) {
  const block = source.match(/AVATAR_COLORS[^{]*\{([\s\S]*?)\n\};/);
  if (!block) throw new Error('No AVATAR_COLORS in avatar-colors.ts');
  const avatars = [...block[1].matchAll(/(\w+):\s*'#([0-9a-f]{6})'/gi)].map(([, key, hex]) => ({
    key,
    argb: `0xFF${hex.toUpperCase()}`,
  }));
  if (avatars.length === 0) throw new Error('AVATAR_COLORS is empty');
  return avatars;
}

export function toDart({ colors, radii, avatars = [] }) {
  const fields = colors.map(({ name }) => name);
  const lines = [
    '// Generated by tool/shared.mjs from packages/ui/src/theme.css. Do not edit:',
    '// change the web theme, then run `melos run shared`.',
    '// dart format off',
    '',
    "import 'package:flutter/material.dart';",
    '',
    '/// The colours of the design system, with the same names as the web apps use. The',
    "/// app follows the phone's light or dark setting: `context.kcp` gives the right set.",
    'final class KcpPalette extends ThemeExtension<KcpPalette> {',
    '  const KcpPalette({',
    ...fields.map((name) => `    required this.${name},`),
    '  });',
    '',
    ...fields.map((name) => `  final Color ${name};`),
    '',
    '  @override',
    '  KcpPalette copyWith() => this;',
    '',
    '  @override',
    '  KcpPalette lerp(KcpPalette? other, double t) {',
    '    if (other == null) return this;',
    '    return KcpPalette(',
    ...fields.map((name) => `      ${name}: Color.lerp(${name}, other.${name}, t)!,`),
    '    );',
    '  }',
    '}',
    '',
    '/// Light: a cream-and-sand ground.',
    'const kcpLight = KcpPalette(',
    ...colors.map(({ name, light }) => `  ${name}: Color(${light}),`),
    ');',
    '',
    '/// Dark: the same names; the 100–900 ramps flip.',
    'const kcpDark = KcpPalette(',
    ...colors.map(({ name, dark }) => `  ${name}: Color(${dark}),`),
    ');',
    '',
    "/// Corner radii, in logical pixels (the web's rounded-card, rounded-row…).",
    'abstract final class KcpRadius {',
    ...radii.map(({ name, px }) => `  static const double ${name} = ${px.toFixed(1)};`),
    '}',
    '',
    '/// Background colour of each preset avatar (a white picture sits on it).',
    'const Map<String, Color> kcpAvatarColors = {',
    ...avatars.map(({ key, argb }) => `  '${key}': Color(${argb}),`),
    '};',
    '',
  ];
  return lines.join('\n');
}

/*
 * Icons: the web's Lucide set (packages/ui/src/icons.tsx), as SVG path data that the
 * app draws itself (lib/widgets/kcp_icon.dart), so both look the same.
 */
const num = (n) => Number(Number(n).toFixed(3)).toString();

/** One SVG element of a 24×24 icon as path data. */
export function elementToPath(tag, attrs) {
  const a = (name, fallback = 0) => Number(attrs[name] ?? fallback);
  switch (tag) {
    case 'path':
      return attrs.d;
    case 'line':
      return `M${num(a('x1'))} ${num(a('y1'))}L${num(a('x2'))} ${num(a('y2'))}`;
    case 'polyline':
    case 'polygon': {
      const points = attrs.points
        .trim()
        .split(/[\s,]+/)
        .map(Number);
      let d = '';
      for (let i = 0; i < points.length; i += 2)
        d += `${i === 0 ? 'M' : 'L'}${num(points[i])} ${num(points[i + 1])}`;
      return tag === 'polygon' ? `${d}Z` : d;
    }
    case 'circle': {
      const [cx, cy, r] = [a('cx'), a('cy'), a('r')];
      return `M${num(cx - r)} ${num(cy)}A${num(r)} ${num(r)} 0 1 0 ${num(cx + r)} ${num(cy)}A${num(r)} ${num(r)} 0 1 0 ${num(cx - r)} ${num(cy)}Z`;
    }
    case 'rect': {
      const [x, y, w, h] = [a('x'), a('y'), a('width'), a('height')];
      const rx = Math.min(Number(attrs.rx ?? attrs.ry ?? 0), w / 2);
      const ry = Math.min(Number(attrs.ry ?? attrs.rx ?? 0), h / 2);
      if (!rx) return `M${num(x)} ${num(y)}H${num(x + w)}V${num(y + h)}H${num(x)}Z`;
      const arc = (tx, ty) => `A${num(rx)} ${num(ry)} 0 0 1 ${num(tx)} ${num(ty)}`;
      return (
        `M${num(x + rx)} ${num(y)}H${num(x + w - rx)}${arc(x + w, y + ry)}` +
        `V${num(y + h - ry)}${arc(x + w - rx, y + h)}H${num(x + rx)}${arc(x, y + h - ry)}` +
        `V${num(y + ry)}${arc(x + rx, y)}Z`
      );
    }
    default:
      throw new Error(`Icons can't use <${tag}> yet`);
  }
}

/** PATHS and DIRECTIONAL from icons.tsx: [{ name, paths }], and the mirrored names. */
export function readIcons(source) {
  const block = source.match(/const PATHS = \{([\s\S]*?)\n\} as const;/);
  if (!block) throw new Error('No PATHS in icons.tsx');
  const icons = [];
  for (const [, name, quoted] of block[1].matchAll(/^\s+'?(\w+)'?:\s*\n?\s*'([^']*)',/gm)) {
    const paths = [...quoted.matchAll(/<(\w+)([^>]*?)\/>/g)].map(([, tag, rest]) => {
      const attrs = Object.fromEntries(
        [...rest.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, key, value]) => [key, value]),
      );
      return elementToPath(tag, attrs);
    });
    icons.push({ name, paths });
  }
  const directional = source.match(/DIRECTIONAL = new Set<IconName>\(\[([\s\S]*?)\]\)/);
  if (icons.length === 0 || !directional) throw new Error('No icons or DIRECTIONAL in icons.tsx');
  return { icons, directional: [...directional[1].matchAll(/'(\w+)'/g)].map(([, n]) => n) };
}

export function iconsToDart({ icons, directional }) {
  return [
    '// Generated by tool/shared.mjs from packages/ui/src/icons.tsx (Lucide, ISC licence).',
    '// Do not edit: change the web icons, then run `melos run shared`.',
    '// dart format off',
    '',
    '/// Each icon as SVG path data on a 24×24 grid, drawn with round 2.75 strokes.',
    'const Map<String, List<String>> kcpIconPaths = {',
    ...icons.map(({ name, paths }) => `  '${name}': [${paths.map((d) => `'${d}'`).join(', ')}],`),
    '};',
    '',
    '/// Icons that point along the reading direction: mirrored in Arabic and Urdu.',
    `const Set<String> kcpDirectionalIcons = {${directional.map((n) => `'${n}'`).join(', ')}};`,
    '',
  ].join('\n');
}

/** Badge names and descriptions per language, from the web apps' messages. */
export function badgesToDart(messagesByLanguage) {
  const dartString = (text) =>
    `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;
  const lines = [
    '// Generated by tool/shared.mjs from packages/i18n/messages/*.json ("badges").',
    '// Do not edit: change the web messages, then run `melos run shared`.',
    '// dart format off',
    '',
    "/// A badge's name and what it is for.",
    'typedef BadgeText = ({String name, String description});',
    '',
    '/// Badge texts by language, then by badge key.',
    'const Map<String, Map<String, BadgeText>> badgeTexts = {',
  ];
  for (const language of LANGUAGES) {
    const badges = messagesByLanguage[language]?.badges ?? {};
    lines.push(`  '${language}': {`);
    for (const [key, value] of Object.entries(badges)) {
      if (!value || typeof value !== 'object' || !value.name) continue;
      lines.push(
        `    '${key}': (name: ${dartString(value.name)}, description: ${dartString(value.description ?? '')}),`,
      );
    }
    lines.push('  },');
  }
  lines.push('};', '');
  return lines.join('\n');
}

const outputs = [
  [
    outPath,
    toDart({
      ...readTokens(readFileSync(themePath, 'utf8')),
      avatars: readAvatarColors(readFileSync(avatarColorsPath, 'utf8')),
    }),
  ],
  [iconsOutPath, iconsToDart(readIcons(readFileSync(iconsPath, 'utf8')))],
  [
    badgesOutPath,
    badgesToDart(
      Object.fromEntries(
        LANGUAGES.map((language) => [
          language,
          JSON.parse(
            readFileSync(join(repoRoot, `packages/i18n/messages/${language}.json`), 'utf8'),
          ),
        ]),
      ),
    ),
  ],
];

if (process.argv.includes('--check')) {
  const stale = outputs.filter(([path, content]) => {
    try {
      return readFileSync(path, 'utf8') !== content;
    } catch {
      return true;
    }
  });
  if (stale.length > 0) {
    console.error(
      `Out of date: ${stale.map(([path]) => path.slice(path.indexOf('lib/'))).join(', ')}. Run \`node apps/mobile/tool/shared.mjs\`.`,
    );
    process.exit(1);
  }
  console.log('Shared tokens and texts are up to date.');
} else {
  for (const [path, content] of outputs) writeFileSync(path, content);
  console.log(
    'Wrote lib/theme/tokens.g.dart, lib/theme/icons.g.dart and lib/l10n/badge_texts.g.dart',
  );
}
