/** API error codes that have their own translated message under "errors.*". */
export const KNOWN_ERROR_CODES = [
  'INVALID_CREDENTIALS',
  'EMAIL_NOT_VERIFIED',
  'ACCOUNT_DISABLED',
  'INVALID_OR_EXPIRED_TOKEN',
  'TOO_MANY_REQUESTS',
  'UNSUPPORTED_COUNTRY',
  'UNSUPPORTED_LANGUAGE',
  'NICKNAME_INVALID_FORMAT',
  'NICKNAME_INAPPROPRIATE',
  'NICKNAME_LOOKS_LIKE_REAL_NAME',
  'NICKNAME_CONTAINS_CONTACT_INFO',
  'TOO_MANY_CHILDREN',
  'BIRTH_YEAR_NOT_ALLOWED',
  'CONFIRMATION_MISMATCH',
  'INVALID_LOCATION',
  'PASSWORD_TOO_WEAK',
  'WRONG_PASSWORD',
  'INVALID_CODE',
  'MFA_EXPIRED',
  'MENTOR_NOT_READY',
  'MENTOR_AT_CAPACITY',
  'REVIEW_TAKEN',
  'NOT_YOUR_REVIEW',
  'SCORES_NEEDED',
  'NO_SUCH_LINE',
  'REVIEW_PENDING',
  'CONSENT_PENDING',
  'PICTURE_LOCKED',
  'PAIRING_NOT_FOUND',
  'CONSENT_FORM_TYPE',
  'CONSENT_FORM_TOO_BIG',
  'CONSENT_FORM_MISSING',
  'CONSENT_METHOD_UNAVAILABLE',
  'CONSENT_UNDER_REVIEW',
  'CONSENT_NOT_NEEDED',
  'PICTURE_PASSWORD_WEAK',
  'PICTURE_PASSWORD_INVALID',
  'CARDS_UNAVAILABLE',
  'FRIEND_CODE_NOT_FOUND',
  'FRIEND_SELF',
  'ALREADY_FRIENDS',
  'FRIEND_REQUEST_EXISTS',
  'TOO_MANY_FRIEND_REQUESTS',
  'TOO_MANY_FRIENDS',
  'FRIEND_REQUEST_CLOSED',
  'PHRASES_ONLY',
  'CHAT_MUTED',
  'TOO_MANY_MESSAGES',
  'ROOM_ARCHIVED',
  'REPORT_SELF',
  'EVENT_CLOSED',
  'TOO_YOUNG_FOR_EVENT',
  'ALREADY_IN_TEAM',
  'TEAM_NAME_INVALID',
  'TEAM_NAME_BLOCKED',
  'TEAM_NAME_TAKEN',
  'TEAM_CODE_NOT_FOUND',
  'TEAM_FULL',
  'EVENT_NOT_RUNNING',
  'GIT_NOT_SET_UP',
  'PULL_EXISTS',
  'BRANCH_NOT_FOUND',
  'TEXT_BLOCKED',
  'OWN_PULL',
  'APPROVAL_NEEDED',
  'CHANGES_REQUESTED',
  'CONFLICTS',
  'PULL_CLOSED',
  'GIT_REFUSED',
  'NOT_JUDGING',
  'CLASS_CODE_NOT_FOUND',
  'ALREADY_IN_CLASS',
  'CLASS_FULL',
  'CLASS_CLOSED',
  'CLASS_NOT_FOUND',
  'SCHOOL_NOT_FOUND',
  'ALREADY_ASSIGNED',
  'LESSON_NOT_FOUND',
  'REQUEST_NOT_FOUND',
  'READINESS_NOT_AVAILABLE',
  'READINESS_NOT_STARTED',
  'TIME_UP',
] as const;

export type KnownErrorCode = (typeof KNOWN_ERROR_CODES)[number];

/** Maps an API error code (or a thrown network error) to a message key. */
export function errorMessageKey(code: string | undefined, networkError = false) {
  if (networkError) return 'network' as const;
  return (KNOWN_ERROR_CODES as readonly string[]).includes(code ?? '')
    ? (code as KnownErrorCode)
    : ('generic' as const);
}

/** Nickname problems belong next to the nickname field rather than at the top of the form. */
export function isNicknameError(code: string | undefined): boolean {
  return code?.startsWith('NICKNAME_') ?? false;
}
