// Generated by tool/shared.mjs from packages/ui/src/theme.css. Do not edit:
// change the web theme, then run `melos run shared`.
// dart format off

import 'package:flutter/material.dart';

/// The colours of the design system, with the same names as the web apps use. The
/// app follows the phone's light or dark setting: `context.kcp` gives the right set.
final class KcpPalette extends ThemeExtension<KcpPalette> {
  const KcpPalette({
    required this.canvas,
    required this.surface,
    required this.raised,
    required this.ink,
    required this.muted,
    required this.line,
    required this.track,
    required this.brand,
    required this.brand100,
    required this.brand200,
    required this.brand300,
    required this.brand400,
    required this.brand500,
    required this.brand600,
    required this.brand700,
    required this.brand800,
    required this.brand900,
    required this.brandText,
    required this.primary,
    required this.primaryHover,
    required this.primaryActive,
    required this.onPrimary,
    required this.sage,
    required this.sage100,
    required this.sage200,
    required this.sage300,
    required this.sage400,
    required this.sage500,
    required this.sage600,
    required this.sage700,
    required this.sage800,
    required this.sage900,
    required this.sageText,
    required this.sand100,
    required this.sand200,
    required this.sand300,
    required this.sand400,
    required this.sand500,
    required this.sand600,
    required this.sand700,
    required this.sand800,
    required this.sand900,
    required this.danger,
    required this.dangerSoft,
    required this.dangerText,
    required this.onDanger,
    required this.warnSoft,
    required this.warnText,
    required this.codeBg,
    required this.codeGutter,
    required this.codeTag,
    required this.codeAttr,
    required this.codeStr,
    required this.codeCom,
  });

  final Color canvas;
  final Color surface;
  final Color raised;
  final Color ink;
  final Color muted;
  final Color line;
  final Color track;
  final Color brand;
  final Color brand100;
  final Color brand200;
  final Color brand300;
  final Color brand400;
  final Color brand500;
  final Color brand600;
  final Color brand700;
  final Color brand800;
  final Color brand900;
  final Color brandText;
  final Color primary;
  final Color primaryHover;
  final Color primaryActive;
  final Color onPrimary;
  final Color sage;
  final Color sage100;
  final Color sage200;
  final Color sage300;
  final Color sage400;
  final Color sage500;
  final Color sage600;
  final Color sage700;
  final Color sage800;
  final Color sage900;
  final Color sageText;
  final Color sand100;
  final Color sand200;
  final Color sand300;
  final Color sand400;
  final Color sand500;
  final Color sand600;
  final Color sand700;
  final Color sand800;
  final Color sand900;
  final Color danger;
  final Color dangerSoft;
  final Color dangerText;
  final Color onDanger;
  final Color warnSoft;
  final Color warnText;
  final Color codeBg;
  final Color codeGutter;
  final Color codeTag;
  final Color codeAttr;
  final Color codeStr;
  final Color codeCom;

  @override
  KcpPalette copyWith() => this;

  @override
  KcpPalette lerp(KcpPalette? other, double t) {
    if (other == null) return this;
    return KcpPalette(
      canvas: Color.lerp(canvas, other.canvas, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      raised: Color.lerp(raised, other.raised, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      muted: Color.lerp(muted, other.muted, t)!,
      line: Color.lerp(line, other.line, t)!,
      track: Color.lerp(track, other.track, t)!,
      brand: Color.lerp(brand, other.brand, t)!,
      brand100: Color.lerp(brand100, other.brand100, t)!,
      brand200: Color.lerp(brand200, other.brand200, t)!,
      brand300: Color.lerp(brand300, other.brand300, t)!,
      brand400: Color.lerp(brand400, other.brand400, t)!,
      brand500: Color.lerp(brand500, other.brand500, t)!,
      brand600: Color.lerp(brand600, other.brand600, t)!,
      brand700: Color.lerp(brand700, other.brand700, t)!,
      brand800: Color.lerp(brand800, other.brand800, t)!,
      brand900: Color.lerp(brand900, other.brand900, t)!,
      brandText: Color.lerp(brandText, other.brandText, t)!,
      primary: Color.lerp(primary, other.primary, t)!,
      primaryHover: Color.lerp(primaryHover, other.primaryHover, t)!,
      primaryActive: Color.lerp(primaryActive, other.primaryActive, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      sage: Color.lerp(sage, other.sage, t)!,
      sage100: Color.lerp(sage100, other.sage100, t)!,
      sage200: Color.lerp(sage200, other.sage200, t)!,
      sage300: Color.lerp(sage300, other.sage300, t)!,
      sage400: Color.lerp(sage400, other.sage400, t)!,
      sage500: Color.lerp(sage500, other.sage500, t)!,
      sage600: Color.lerp(sage600, other.sage600, t)!,
      sage700: Color.lerp(sage700, other.sage700, t)!,
      sage800: Color.lerp(sage800, other.sage800, t)!,
      sage900: Color.lerp(sage900, other.sage900, t)!,
      sageText: Color.lerp(sageText, other.sageText, t)!,
      sand100: Color.lerp(sand100, other.sand100, t)!,
      sand200: Color.lerp(sand200, other.sand200, t)!,
      sand300: Color.lerp(sand300, other.sand300, t)!,
      sand400: Color.lerp(sand400, other.sand400, t)!,
      sand500: Color.lerp(sand500, other.sand500, t)!,
      sand600: Color.lerp(sand600, other.sand600, t)!,
      sand700: Color.lerp(sand700, other.sand700, t)!,
      sand800: Color.lerp(sand800, other.sand800, t)!,
      sand900: Color.lerp(sand900, other.sand900, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      dangerSoft: Color.lerp(dangerSoft, other.dangerSoft, t)!,
      dangerText: Color.lerp(dangerText, other.dangerText, t)!,
      onDanger: Color.lerp(onDanger, other.onDanger, t)!,
      warnSoft: Color.lerp(warnSoft, other.warnSoft, t)!,
      warnText: Color.lerp(warnText, other.warnText, t)!,
      codeBg: Color.lerp(codeBg, other.codeBg, t)!,
      codeGutter: Color.lerp(codeGutter, other.codeGutter, t)!,
      codeTag: Color.lerp(codeTag, other.codeTag, t)!,
      codeAttr: Color.lerp(codeAttr, other.codeAttr, t)!,
      codeStr: Color.lerp(codeStr, other.codeStr, t)!,
      codeCom: Color.lerp(codeCom, other.codeCom, t)!,
    );
  }
}

/// Light: a cream-and-sand ground.
const kcpLight = KcpPalette(
  canvas: Color(0xFFF5EAD8),
  surface: Color(0xFFEBDDC5),
  raised: Color(0xFFF9F4ED),
  ink: Color(0xFF201E1D),
  muted: Color(0xFF645C50),
  line: Color(0x24201E1D),
  track: Color(0x1A201E1D),
  brand: Color(0xFFC67139),
  brand100: Color(0xFFFFF2EB),
  brand200: Color(0xFFFFE1D0),
  brand300: Color(0xFFFFC6A5),
  brand400: Color(0xFFF6A06B),
  brand500: Color(0xFFD67F48),
  brand600: Color(0xFFB2622D),
  brand700: Color(0xFF8C491A),
  brand800: Color(0xFF643312),
  brand900: Color(0xFF402310),
  brandText: Color(0xFF8C491A),
  primary: Color(0xFFA05626),
  primaryHover: Color(0xFF944D1F),
  primaryActive: Color(0xFF8C491A),
  onPrimary: Color(0xFFFFFAF3),
  sage: Color(0xFF7A8A5E),
  sage100: Color(0xFFF0FAE1),
  sage200: Color(0xFFE1EECC),
  sage300: Color(0xFFCCDBB2),
  sage400: Color(0xFFAEBF92),
  sage500: Color(0xFF8FA073),
  sage600: Color(0xFF728157),
  sage700: Color(0xFF56633F),
  sage800: Color(0xFF3D472B),
  sage900: Color(0xFF272E1B),
  sageText: Color(0xFF56633F),
  sand100: Color(0xFFF9F4ED),
  sand200: Color(0xFFEEE7DB),
  sand300: Color(0xFFDCD3C4),
  sand400: Color(0xFFC0B6A5),
  sand500: Color(0xFFA19786),
  sand600: Color(0xFF82796A),
  sand700: Color(0xFF645C50),
  sand800: Color(0xFF474238),
  sand900: Color(0xFF2E2B25),
  danger: Color(0xFFB3261E),
  dangerSoft: Color(0xFFFBE3DC),
  dangerText: Color(0xFF7F1D16),
  onDanger: Color(0xFFFFFAF3),
  warnSoft: Color(0xFFFBE8C4),
  warnText: Color(0xFF6B4508),
  codeBg: Color(0xFFFBF6EE),
  codeGutter: Color(0xFF6F6659),
  codeTag: Color(0xFF8C491A),
  codeAttr: Color(0xFF56633F),
  codeStr: Color(0xFF7A4F8A),
  codeCom: Color(0xFF645C50),
);

/// Dark: the same names; the 100–900 ramps flip.
const kcpDark = KcpPalette(
  canvas: Color(0xFF1A1815),
  surface: Color(0xFF25221E),
  raised: Color(0xFF2E2A25),
  ink: Color(0xFFF2E8D8),
  muted: Color(0xFFB9AE9C),
  line: Color(0x21F2E8D8),
  track: Color(0x1FF2E8D8),
  brand: Color(0xFFE08D55),
  brand100: Color(0xFF3A2213),
  brand200: Color(0xFF4D2C16),
  brand300: Color(0xFF6B3A1A),
  brand400: Color(0xFFB2622D),
  brand500: Color(0xFFD67F48),
  brand600: Color(0xFFF6A06B),
  brand700: Color(0xFFFFC6A5),
  brand800: Color(0xFFFFE1D0),
  brand900: Color(0xFFFFF2EB),
  brandText: Color(0xFFF6A06B),
  primary: Color(0xFFE08D55),
  primaryHover: Color(0xFFF6A06B),
  primaryActive: Color(0xFFFFC6A5),
  onPrimary: Color(0xFF1A1815),
  sage: Color(0xFFA3B485),
  sage100: Color(0xFF242B1A),
  sage200: Color(0xFF2F3822),
  sage300: Color(0xFF3D472B),
  sage400: Color(0xFF56633F),
  sage500: Color(0xFF8FA073),
  sage600: Color(0xFFAEBF92),
  sage700: Color(0xFFCCDBB2),
  sage800: Color(0xFFE1EECC),
  sage900: Color(0xFFF0FAE1),
  sageText: Color(0xFFC2D2A6),
  sand100: Color(0xFF2E2B25),
  sand200: Color(0xFF3A362F),
  sand300: Color(0xFF474238),
  sand400: Color(0xFF645C50),
  sand500: Color(0xFF82796A),
  sand600: Color(0xFFA19786),
  sand700: Color(0xFFC0B6A5),
  sand800: Color(0xFFDCD3C4),
  sand900: Color(0xFFF9F4ED),
  danger: Color(0xFFF08A7E),
  dangerSoft: Color(0xFF3D1F1B),
  dangerText: Color(0xFFFFC9C1),
  onDanger: Color(0xFF1A1815),
  warnSoft: Color(0xFF3A2E14),
  warnText: Color(0xFFF3D08C),
  codeBg: Color(0xFF14120F),
  codeGutter: Color(0xFF948B7C),
  codeTag: Color(0xFFF6A06B),
  codeAttr: Color(0xFFB9CB98),
  codeStr: Color(0xFFD6B3E0),
  codeCom: Color(0xFFA19786),
);

/// Corner radii, in logical pixels (the web's rounded-card, rounded-row…).
abstract final class KcpRadius {
  static const double card = 32.0;
  static const double panel = 28.0;
  static const double inner = 26.0;
  static const double row = 22.0;
  static const double well = 20.0;
  static const double hero = 36.0;
}

/// Background colour of each preset avatar (a white picture sits on it).
const Map<String, Color> kcpAvatarColors = {
  'rocket': Color(0xFF8C491A),
  'star': Color(0xFF8A5A14),
  'bolt': Color(0xFF6B4A7A),
  'planet': Color(0xFF2F6068),
  'robot': Color(0xFF5B5347),
  'leaf': Color(0xFF56633F),
  'moon': Color(0xFF3F4A6B),
  'sun': Color(0xFFA0501A),
  'cube': Color(0xFF8E3D55),
  'gamepad': Color(0xFF3D6655),
  'music': Color(0xFF7B4668),
  'code': Color(0xFF34506E),
};
